In [1]:
print("hello")

hello

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/raw/CEAS_08.csv")

FileNotFoundError: [Errno 2] No such file or directory: '../data/raw/CEAS_08.csv'

In [4]:
import sys

print(sys.executable)

C:\Users\Admin\Documents\phishing-detection-system\.venv\Scripts\python.exe

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv("../data/raw/CEAS_08.csv")

FileNotFoundError: [Errno 2] No such file or directory: '../data/raw/CEAS_08.csv'

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/raw/CEAS_08.csv")

In [3]:
df.head()

,sender,receiver,date,subject,body,label,urls
0,Young Esposito <Young@iworld.de>,user4@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 16:31:02 -0700",Never agree to be a loser,"Buck up, your troubles caused by small dimensi...",1,1
1,Mok <ipline's1983@icable.ph>,user2.2@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 18:31:03 -0500",Befriend Jenna Jameson,\nUpgrade your sex and pleasures with these te...,1,1
2,Daily Top 10 <Karmandeep-opengevl@universalnet...,user2.9@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 20:28:00 -1200",CNN.com Daily Top 10,>+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+...,1,1
3,Michael Parker <ivqrnai@pobox.com>,SpamAssassin Dev <xrh@spamassassin.apache.org>,"Tue, 05 Aug 2008 17:31:20 -0600",Re: svn commit: r619753 - in /spamassassin/tru...,Would anyone object to removing .so from this ...,0,1
4,Gretchen Suggs <externalsep1@loanofficertool.com>,user2.2@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 19:31:21 -0400",SpecialPricesPharmMoreinfo,\nWelcomeFastShippingCustomerSupport\nhttp://7...,1,1

In [4]:
df.shape

(39154, 7)

In [5]:
df.columns

Index(['sender', 'receiver', 'date', 'subject', 'body', 'label', 'urls'], dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 39154 entries, 0 to 39153
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   sender    39154 non-null  str
 1   receiver  38692 non-null  str
 2   date      39154 non-null  str
 3   subject   39126 non-null  str
 4   body      39154 non-null  str
 5   label     39154 non-null  int64
 6   urls      39154 non-null  int64
dtypes: int64(2), str(5)
memory usage: 2.1 MB

In [7]:
df.isnull().sum()

sender        0
receiver    462
date          0
subject      28
body          0
label         0
urls          0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.nunique()

In [ ]:
df.describe(include="all").T

In [ ]:
for col in df.columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False).head(20))

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("../data/raw/CEAS_08.csv")

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.nunique()

sender      24578
receiver     3693
date        38658
subject     15436
body        39154
label           2
urls            2
dtype: int64

In [7]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
sender,39154,24578,qydlqcws-iacfym@issues.apache.org,462,NaN,NaN,NaN,NaN,NaN,NaN,NaN
receiver,38692,3693,user6@gvc.ceas-challenge.cc,1375,NaN,NaN,NaN,NaN,NaN,NaN,NaN
date,39154,38658,"Thu, 07 Aug 2008 21:38:18 -0100",8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
subject,39126,15436,CNN.com Daily Top 10,2930,NaN,NaN,NaN,NaN,NaN,NaN,NaN
body,39154,39154,"Buck up, your troubles caused by small dimensi...",1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
label,39154.0,NaN,NaN,NaN,0.557848,0.496649,0.0,0.0,1.0,1.0,1.0
urls,39154.0,NaN,NaN,NaN,0.66997,0.47023,0.0,0.0,1.0,1.0,1.0

In [8]:
for col in df.columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False).head(20))

--- sender ---
sender
qydlqcws-iacfym@issues.apache.org                 462
Guido van Rossum <hoauf@python.org>               295
"\\"Martin v. Löwis\\"" <qpnysl@v.loewis.de>      276
"Carlos E. R." <vyjwd.trpcau@telefonica.net>      208
Aaron Kulkis <cmiqlkx91@hotpop.com>               183
Rafael Garcia-Suarez <pvhuhqgncrxnu@gmail.com>    158
Christian Heimes <wluhe@cheimes.de>               152
Barry Warsaw <pjaxq@python.org>                   131
iybz@pobox.com                                    124
Per Jessen <uee@computer.org>                     113
vvrpgs@porcupine.org                              112
Greg Ewing <lwbw.yflqt@canterbury.ac.nz>          112
Benjamin Peterson <mfphjffbrfsvyrjf@gmail.com>    110
Nick Coghlan <uytankmf@gmail.com>                 108
mouss <qpeqr@netoyen.net>                         106
Perl Jobs <xycn-vtnhz@perl.org>                    90
Trent Nelson <ktctpxa@onresolve.com>               88
SpamExperts via Twitter <uiaregi@twitter.com>      84
Tim Golden <cggc@timgolden.me.uk>                  83
user7@gvc.ceas-challenge.cc                        76
Name: count, dtype: int64

--- receiver ---
receiver
user6@gvc.ceas-challenge.cc           1375
wkilxloc@opensuse.org                 1230
user2.1@gvc.ceas-challenge.cc         1037
user2.2@gvc.ceas-challenge.cc          922
user2.4@gvc.ceas-challenge.cc          738
user2.13@gvc.ceas-challenge.cc         686
user7@gvc.ceas-challenge.cc            674
user8.2-ext1@gvc.ceas-challenge.cc     655
user7-ext4@gvc.ceas-challenge.cc       655
user7-ext3@gvc.ceas-challenge.cc       652
user2.1-ext1@gvc.ceas-challenge.cc     639
user2.6@gvc.ceas-challenge.cc          626
user8.2-ext2@gvc.ceas-challenge.cc     567
user5@gvc.ceas-challenge.cc            552
zqoqi@spamassassin.apache.org          546
xrh@spamassassin.apache.org            512
user2.10@gvc.ceas-challenge.cc         498
user8.1@gvc.ceas-challenge.cc          496
user2.12@gvc.ceas-challenge.cc         484
user2.5@gvc.ceas-challenge.cc          475
Name: count, dtype: int64

--- date ---
date
Thu, 07 Aug 2008 21:38:18 -0100    8
Fri, 08 Aug 2008 05:22:59 -0400    4
Fri, 08 Aug 2008 02:35:56 -0400    4
Tue, 05 Aug 2008 16:08:14 -0800    3
Wed, 06 Aug 2008 12:14:16 +0500    3
Wed, 06 Aug 2008 15:47:48 -0500    3
Wed, 06 Aug 2008 18:51:17 +0500    3
Thu, 07 Aug 2008 02:28:14 +0100    3
Thu, 07 Aug 2008 22:38:03 -0200    3
Thu, 07 Aug 2008 21:38:05 -0100    3
Thu, 07 Aug 2008 21:38:17 -0100    3
Thu, 07 Aug 2008 21:38:21 -0100    3
Fri, 08 Aug 2008 03:55:50 -0400    3
Tue, 05 Aug 2008 18:45:54 -0500    2
Tue, 05 Aug 2008 20:04:14 -0400    2
Wed, 06 Aug 2008 00:05:43 +0000    2
Wed, 06 Aug 2008 00:06:47 +0000    2
Tue, 05 Aug 2008 17:08:23 -0700    2
Tue, 05 Aug 2008 20:09:45 -0400    2
Tue, 05 Aug 2008 20:15:28 -0400    2
Name: count, dtype: int64

--- subject ---
subject
CNN.com Daily Top 10                                                2930
CNN Alerts: My Custom Alert                                         1406
Re:                                                                  580
123                                                                  255
Re:                                                                  125
Re: [opensuse] openSUSE 11.0 and the Non-ready KDE4                  103
How To Enlarge Penis Size                                            100
Direct message from SpamExperts via web                               84
Re: [opensuse] Defragging: possible?  necessary?                      76
Re: [opensuse]  [OT] How much power does a PC really consume?         74
Re: [opensuse] ext3 check forced = frustration                        69
Qualitative replica watches for most exacting people                  65
Penis Enlargment Reviews                                              62
Re: [Python-Dev] PEP 365 (Adding the pkg_resources module)            62
Produce Stronger, Rock Hard Erections.                                61
You our client!                                                       61
Re: [Python-3000] u'text' as an alias for 'text'?                     61
*3 FREE Bottles Of VPXL !!                                            60
Penis Enlargement Is Possible ! Learn How and What Products Work      59
Karma sutra techniques for G-spots                                    56
Name: count, dtype: int64

--- body ---
body

In [9]:
df["label"].value_counts(dropna=False)

label
1    21842
0    17312
Name: count, dtype: int64

In [10]:
df["label"].value_counts(normalize=True, dropna=False)

label
1    0.557848
0    0.442152
Name: proportion, dtype: float64

In [11]:
df[["subject", "body", "label"]].isnull().sum()

subject    28
body        0
label       0
dtype: int64

In [12]:
email_df = df.copy()

In [13]:
email_df["text"] = (
    email_df["subject"].fillna("").astype(str)
    + " "
    + email_df["body"].fillna("").astype(str)
)

In [14]:
email_df[["subject", "body", "text", "label"]].head()

,subject,body,text,label
0,Never agree to be a loser,"Buck up, your troubles caused by small dimensi...","Never agree to be a loser Buck up, your troubl...",1
1,Befriend Jenna Jameson,\nUpgrade your sex and pleasures with these te...,Befriend Jenna Jameson \nUpgrade your sex and ...,1
2,CNN.com Daily Top 10,>+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+...,CNN.com Daily Top 10 >+=+=+=+=+=+=+=+=+=+=+=+=...,1
3,Re: svn commit: r619753 - in /spamassassin/tru...,Would anyone object to removing .so from this ...,Re: svn commit: r619753 - in /spamassassin/tru...,0
4,SpecialPricesPharmMoreinfo,\nWelcomeFastShippingCustomerSupport\nhttp://7...,SpecialPricesPharmMoreinfo \nWelcomeFastShippi...,1

In [15]:
email_df = email_df.dropna(subset=["label"])

In [16]:
email_df = email_df.drop_duplicates(subset=["text"])

In [17]:
email_df.shape

(39154, 8)

In [18]:
email_df["label"].value_counts()

label
1    21842
0    17312
Name: count, dtype: int64

In [19]:
df.groupby("label")[["subject", "body"]].first()

,subject,body
label,,
0,Re: svn commit: r619753 - in /spamassassin/tru...,Would anyone object to removing .so from this ...
1,Never agree to be a loser,"Buck up, your troubles caused by small dimensi..."

In [20]:
df.groupby("label").size()

label
0    17312
1    21842
dtype: int64

In [21]:
email_df = df.copy()

In [22]:
email_df["subject"] = email_df["subject"].fillna("")
email_df["body"] = email_df["body"].fillna("")

In [23]:
email_df["text"] = (
    email_df["subject"].astype(str) + " " +
    email_df["body"].astype(str)
)

In [24]:
email_df = email_df[email_df["text"].str.strip() != ""].copy()

In [25]:
email_df = email_df.drop_duplicates(subset=["text"]).copy()

In [26]:
print("Dataset shape:", email_df.shape)
print("\nClass distribution:")
print(email_df["label"].value_counts())

Dataset shape: (39154, 8)

Class distribution:
label
1    21842
0    17312
Name: count, dtype: int64

In [27]:
email_df["text_length"] = email_df["text"].str.len()

email_df["text_length"].describe()

count     39154.000000
mean       1610.976350
std        3617.195529
min          22.000000
25%         260.000000
50%         603.000000
75%        1692.000000
max      144051.000000
Name: text_length, dtype: float64

In [28]:
email_df[["text", "label", "text_length"]].head()

                                                text  label  text_length
0  Never agree to be a loser Buck up, your troubl...      1          299
1  Befriend Jenna Jameson \nUpgrade your sex and ...      1          105
2  CNN.com Daily Top 10 >+=+=+=+=+=+=+=+=+=+=+=+=...      1         3939
3  Re: svn commit: r619753 - in /spamassassin/tru...      0        24569
4  SpecialPricesPharmMoreinfo \nWelcomeFastShippi...      1          202

In [29]:
X = email_df["text"]
y = email_df["label"]

In [30]:
print("Number of emails:", len(X))
print("Number of labels:", len(y))

Number of emails: 39154
Number of labels: 39154

In [31]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [32]:
print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 31323
Testing samples: 7831

In [33]:
print("\nTraining class distribution:")
print(y_train.value_counts())

print("\nTesting class distribution:")
print(y_test.value_counts())

Training class distribution:
label
1    17473
0    13850
Name: count, dtype: int64

Testing class distribution:
label
1    4369
0    3462
Name: count, dtype: int64

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [35]:
tfidf = TfidfVectorizer(
    lowercase=True,
    stop_words="english",
    max_features=10000,
    ngram_range=(1, 2),
    min_df=2
)

In [36]:
X_train_tfidf = tfidf.fit_transform(X_train)

In [37]:
X_test_tfidf = tfidf.transform(X_test)

In [38]:
print("Training TF-IDF shape:", X_train_tfidf.shape)
print("Testing TF-IDF shape:", X_test_tfidf.shape)

Training TF-IDF shape: (31323, 10000)
Testing TF-IDF shape: (7831, 10000)

In [39]:
from sklearn.svm import LinearSVC

In [40]:
svm_model = LinearSVC(random_state=42)

svm_model.fit(X_train_tfidf, y_train)

LinearSVC(random_state=42)

In [42]:
#make predictions
svm_pred = svm_model.predict(X_test_tfidf)

In [43]:
#train the model
svm_model = LinearSVC(random_state=42)

svm_model.fit(X_train_tfidf, y_train)

LinearSVC(random_state=42)

In [44]:
#make predictions
svm_pred = svm_model.predict(X_test_tfidf)

In [45]:
#random forest
from sklearn.ensemble import RandomForestClassifier

In [46]:
#create and train
rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1,
    class_weight="balanced"
)

rf_model.fit(X_train_tfidf, y_train)

RandomForestClassifier(class_weight='balanced', n_estimators=200, n_jobs=-1,
                       random_state=42)

In [47]:
#predict
rf_pred = rf_model.predict(X_test_tfidf)

In [49]:
#XGBoost(import)
from xgboost import XGBClassifier

In [50]:
#Create the model;
xgb_model = XGBClassifier(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric="logloss",
    n_jobs=-1
)

In [53]:
#train
xgb_model.fit(X_train_tfidf, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=-1,
              num_parallel_tree=None, ...)

In [54]:
#predict
xgb_pred = xgb_model.predict(X_test_tfidf)

In [55]:
#evaluate the evaluation metrics
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

In [56]:
#create a function
def evaluate_model(name, y_true, y_pred):
    print(f"\n{'=' * 50}")
    print(name)
    print(f"{'=' * 50}")
    
    print(f"Accuracy : {accuracy_score(y_true, y_pred):.4f}")
    print(f"Precision: {precision_score(y_true, y_pred):.4f}")
    print(f"Recall   : {recall_score(y_true, y_pred):.4f}")
    print(f"F1-score : {f1_score(y_true, y_pred):.4f}")
    
    print("\nClassification Report:")
    print(classification_report(y_true, y_pred))
    
    print("Confusion Matrix:")
    print(confusion_matrix(y_true, y_pred))

In [57]:
#evaluate
evaluate_model("Support Vector Machine", y_test, svm_pred)

==================================================
Support Vector Machine
==================================================
Accuracy : 0.9971
Precision: 0.9973
Recall   : 0.9975
F1-score : 0.9974

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3462
           1       1.00      1.00      1.00      4369

    accuracy                           1.00      7831
   macro avg       1.00      1.00      1.00      7831
weighted avg       1.00      1.00      1.00      7831

Confusion Matrix:
[[3450   12]
 [  11 4358]]

In [58]:
evaluate_model("Random Forest", y_test, rf_pred)

==================================================
Random Forest
==================================================
Accuracy : 0.9967
Precision: 0.9977
Recall   : 0.9963
F1-score : 0.9970

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3462
           1       1.00      1.00      1.00      4369

    accuracy                           1.00      7831
   macro avg       1.00      1.00      1.00      7831
weighted avg       1.00      1.00      1.00      7831

Confusion Matrix:
[[3452   10]
 [  16 4353]]

In [59]:
evaluate_model("XGBoost", y_test, xgb_pred)

==================================================
XGBoost
==================================================
Accuracy : 0.9934
Precision: 0.9907
Recall   : 0.9975
F1-score : 0.9941

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.99      0.99      3462
           1       0.99      1.00      0.99      4369

    accuracy                           0.99      7831
   macro avg       0.99      0.99      0.99      7831
weighted avg       0.99      0.99      0.99      7831

Confusion Matrix:
[[3421   41]
 [  11 4358]]

In [60]:
#compare the three models
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pandas as pd

results = pd.DataFrame({
    "Model": [
        "Support Vector Machine",
        "Random Forest",
        "XGBoost"
    ],
    "Accuracy": [
        accuracy_score(y_test, svm_pred),
        accuracy_score(y_test, rf_pred),
        accuracy_score(y_test, xgb_pred)
    ],
    "Precision": [
        precision_score(y_test, svm_pred),
        precision_score(y_test, rf_pred),
        precision_score(y_test, xgb_pred)
    ],
    "Recall": [
        recall_score(y_test, svm_pred),
        recall_score(y_test, rf_pred),
        recall_score(y_test, xgb_pred)
    ],
    "F1-score": [
        f1_score(y_test, svm_pred),
        f1_score(y_test, rf_pred),
        f1_score(y_test, xgb_pred)
    ]
})

results = results.round(4)

results

                    Model  Accuracy  Precision  Recall  F1-score
0  Support Vector Machine    0.9971     0.9973  0.9975    0.9974
1           Random Forest    0.9967     0.9977  0.9963    0.9970
2                 XGBoost    0.9934     0.9907  0.9975    0.9941

In [61]:
#Calculate false negative
def get_confusion_metrics(y_true, y_pred):
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    
    return {
        "True Negatives": tn,
        "False Positives": fp,
        "False Negatives": fn,
        "True Positives": tp
    }


svm_cm = get_confusion_metrics(y_test, svm_pred)
rf_cm = get_confusion_metrics(y_test, rf_pred)
xgb_cm = get_confusion_metrics(y_test, xgb_pred)

comparison = pd.DataFrame(
    [svm_cm, rf_cm, xgb_cm],
    index=["SVM", "Random Forest", "XGBoost"]
)

comparison

,True Negatives,False Positives,False Negatives,True Positives
SVM,3450,12,11,4358
Random Forest,3452,10,16,4353
XGBoost,3421,41,11,4358

In [62]:
#save comparism results
results.to_csv("../reports/model_comparison.csv", index=False)

comparison.to_csv("../reports/confusion_matrix_metrics.csv")

print("Model comparison saved.")

Model comparison saved.

In [63]:
import joblib

joblib.dump(tfidf, "../models/tfidf_vectorizer.pkl")

joblib.dump(svm_model, "../models/svm_model.pkl")
joblib.dump(rf_model, "../models/rf_model.pkl")
joblib.dump(xgb_model, "../models/xgb_model.pkl")

print("Models and TF-IDF vectorizer saved successfully.")

Models and TF-IDF vectorizer saved successfully.

In [1]:
df.columns.tolist()

NameError: name 'df' is not defined

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/raw/CEAS_08.csv")

In [4]:
df.columns.tolist()

['sender', 'receiver', 'date', 'subject', 'body', 'label', 'urls']

In [5]:
df["label"].value_counts(dropna=False)

label
1    21842
0    17312
Name: count, dtype: int64

In [6]:
df[["label", "subject", "body"]].head(20)

,label,subject,body
0,1,Never agree to be a loser,"Buck up, your troubles caused by small dimensi..."
1,1,Befriend Jenna Jameson,\nUpgrade your sex and pleasures with these te...
2,1,CNN.com Daily Top 10,>+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+...
3,0,Re: svn commit: r619753 - in /spamassassin/tru...,Would anyone object to removing .so from this ...
4,1,SpecialPricesPharmMoreinfo,\nWelcomeFastShippingCustomerSupport\nhttp://7...
5,1,From Caroline Aragon,\n\n\n\n\nYo wu urS mo ou go rc ebo eForM rgi ...
6,1,Replica Watches,We have fake Swiss Men's and Ladie's Replica \...
7,1,CNN.com Daily Top 10,>+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+...
8,0,[Bug 5780] URI processing turns uuencoded stri...,http://issues.apache.org/SpamAssassin/show_bug...
9,1,CNN.com Daily Top 10,>+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+...
10,1,debt consolidation,\nDo Not consolidate your debt Eliminate it!...
11,1,It combines the best of Creative Suite 3 Desig...,\nAdobe Creative Suite 3 Master Collection for...
12,1,CNN.com Daily Top 10,>+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+...
13,1,CNN.com Daily Top 10,>+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+...
14,1,Fifth / Sixth month,\nexpressherbals\n \nhttp://pacelike.com\n \nF...
15,0,RE: Trial IRC Certificate Application,"\nPlelim,\n\nJust to remind you that if a cert..."
16,1,CNN.com Daily Top 10,>+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+...
17,1,CNN.com Daily Top 10,>+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+...
18,0,"Re: [opensuse] Why can't I use ""shutdown now"" ...",Carlos E. R. wrote: > -----BEGIN PGP SIGNED ME...
19,0,Re: Fwd: [opensuse] Re: openSUSE Boxed Editions,Steve Jacobs wrote: > ---------- Forwarded mes...

In [ ]:
import pandas as pd
import joblib
from pathlib import Path
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# ============================================================
# 1. LOAD EXISTING DATASET
# ============================================================

df = pd.read_csv("../data/raw/CEAS_08.csv")

print("=" * 70)
print("DATASET")
print("=" * 70)
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
print("\nLabel distribution:")
print(df["label"].value_counts().sort_index())


# ============================================================
# 2. LOAD EXISTING SAVED MODELS
# ============================================================

tfidf = joblib.load("../models/tfidf_vectorizer.pkl")
svm_model = joblib.load("../models/svm_model.pkl")
rf_model = joblib.load("../models/rf_model.pkl")
xgb_model = joblib.load("../models/xgb_model.pkl")

print("\n" + "=" * 70)
print("SAVED MODELS")
print("=" * 70)
print("TF-IDF vectorizer: loaded")
print("SVM model: loaded")
print("Random Forest model: loaded")
print("XGBoost model: loaded")


# ============================================================
# 3. IDENTIFY THE TEXT COLUMN
# ============================================================

df["text"] = (
    df["subject"].fillna("").astype(str)
    + " "
    + df["body"].fillna("").astype(str)
)

X = df["text"]
y = df["label"]

X_tfidf = tfidf.transform(X)


# ============================================================
# 4. EVALUATE THE EXISTING MODELS
# ============================================================

models = {
    "SVM": svm_model,
    "Random Forest": rf_model,
    "XGBoost": xgb_model
}

print("\n" + "=" * 70)
print("MODEL EVALUATION")
print("=" * 70)

for name, model in models.items():

    predictions = model.predict(X_tfidf)

    accuracy = accuracy_score(y, predictions)
    precision = precision_score(y, predictions, zero_division=0)
    recall = recall_score(y, predictions, zero_division=0)
    f1 = f1_score(y, predictions, zero_division=0)

    print(f"\n{name}")
    print("-" * 40)
    print(f"Accuracy : {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall   : {recall:.4f}")
    print(f"F1-score : {f1:.4f}")

    print("\nConfusion Matrix:")
    print(confusion_matrix(y, predictions))

    print("\nClassification Report:")
    print(classification_report(
        y,
        predictions,
        target_names=["Legitimate", "Phishing"],
        zero_division=0
    ))


# ============================================================
# 5. VERIFY THE LABEL MAPPING USED BY THE DATASET
# ============================================================

print("\n" + "=" * 70)
print("LABEL MAPPING USED IN THE PROJECT")
print("=" * 70)
print("0 = Legitimate")
print("1 = Phishing/Spam")


# ============================================================
# 6. SAMPLE PREDICTION TEST
# ============================================================

test_email = """
Congratulations! You have won a special prize.
Click the link below to claim your reward immediately.
"""

test_vector = tfidf.transform([test_email])

print("\n" + "=" * 70)
print("SAMPLE PREDICTION")
print("=" * 70)

for name, model in models.items():

    prediction = model.predict(test_vector)[0]

    if prediction == 1:
        result = "Phishing"
    else:
        result = "Legitimate"

    print(f"{name}: {result}")

print("\nML verification completed.")